<a href="https://colab.research.google.com/github/VimalChamyal/Python-for-data-science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (Numerical Python) for numerical manipulation. We can use it for its powerful N-dimensional array. 

In [1]:
!pip install numpy
# To install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
# Load/import numpy library
import numpy as np

In [3]:
mylist = [1,2,4,8]
n = np.array(mylist)
n

array([1, 2, 4, 8])

In [4]:
type(mylist)

list

In [5]:
type(n)

numpy.ndarray

In [6]:
# We can create a numpy array this way as well
n = np.array([1,2,3,4,5,6,7])

Creating a multidimensional array

In [7]:
list_of_lists = np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
list_of_lists.shape
# 3,3 array

(3, 3)

Arrange Function

In [9]:
np.arange(0,10,2)
# Instead of range we have arange here

array([0, 2, 4, 6, 8])

In [10]:
for i in range(0,20, 2):
  print(i)

0
2
4
6
8
10
12
14
16
18


Other functions in numpy

In [11]:
zero = np.zeros(20)
zero
# Create array of 20 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [12]:
ones = np.ones(20)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [13]:
np.ones((3,5))
# (R,C)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.eye(5)
# Generate five 1 at the diagonals

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
mn = np.arange(0,50,2)
len(mn)
# To check the length of an array

25

Reshape

In [16]:
mn = np.arange(0,50)
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [17]:
mn.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Linspace

In [18]:
o = np.linspace(0,6,10)
o
# It will return 10 evenly spaced values from 0 to 6

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [19]:
len(o)

10

In [20]:
o.reshape(5,2)
# inside the braces should multiply to 10 or len(o)

array([[0.        , 0.66666667],
       [1.33333333, 2.        ],
       [2.66666667, 3.33333333],
       [4.        , 4.66666667],
       [5.33333333, 6.        ]])

In [21]:
o

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [22]:
o.resize(2,5)
# Resize will alter the original one whereas reshape won't
o

array([[0.        , 0.66666667, 1.33333333, 2.        , 2.66666667],
       [3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ]])

Generate some random values

In [23]:
np.random.rand(3,2)
# Create an array of given shape and populate it with random sample from a uniform distribution over [0,1]

array([[0.34345989, 0.06567436],
       [0.97076365, 0.88955264],
       [0.70067545, 0.08113215]])

In [24]:
np.random.randn(3,5)
# Create an array of given shape and populate it with random samples from the standard normal distribution

array([[-0.75344354,  0.11579265, -0.42605863,  0.17941441, -0.87754049],
       [-0.31737334,  0.65601744,  1.14932969, -0.7505515 ,  0.95734915],
       [ 0.01778138,  0.25765527,  1.05164006,  0.33498787, -0.62715173]])

In [25]:
ri = np.random.randint(4,15,12)
# Return random integers from low to high, we also tell how many numbers we want

In [26]:
len(ri)

12

In [27]:
ri.reshape(4,3)
# 4*3 = 12

array([[ 6, 12,  4],
       [11,  9, 11],
       [ 7,  4, 13],
       [ 8, 13,  6]])

In [28]:
rio = np.random.randint(4,15, (4,3))
# We can do this way as well
rio

array([[ 4, 10, 14],
       [ 7, 13, 14],
       [10,  8, 12],
       [ 9, 12,  4]])

Indexing and slicing

In [29]:
mn = np.random.randint(4,15,10)
mn

array([ 5,  4,  9,  9,  5,  8,  8,  5, 10,  5])

In [30]:
mn [1:5]
# Selecting items within a range

array([4, 9, 9, 5])

In [31]:
mn [-1]
# Last element

5

In [32]:
mn [0 : : -1]

array([5])

In [33]:
mn.resize(2,5)
mn

array([[ 5,  4,  9,  9,  5],
       [ 8,  8,  5, 10,  5]])

In [34]:
ab = np.arange(0,60,2)

In [35]:
ab.resize(5,6)
ab

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58]])

In [36]:
ab[3,2]
# Accessing the element at 4th row and 3rd column
# Indexing starts from 0

40

In [37]:
ab[3, 1:5]
# Selecting the user defined 4 elements from the 4th row

array([38, 40, 42, 44])

In [38]:
ab

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58]])

In [40]:
ab[2:]
# From the 3rd row

array([[24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58]])

In [41]:
# Selecting from a particular cell
ab[2:,3:]

array([[30, 32, 34],
       [42, 44, 46],
       [54, 56, 58]])

In [43]:
# Conditional indexing
ab[ab>=40]

array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [44]:
ab>=40

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

Broadcasting

In [47]:
ab[ab>40] = 40
ab
# Casting all the values that are greater than 40 to 40

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40]])

Creating a copy of dataset

In [49]:
ab1 = ab[2:,3:]
ab1

array([[30, 32, 34],
       [40, 40, 40],
       [40, 40, 40]])

In [52]:
ab

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40]])